# Automatic dependencies update suggestions

version: 2
updates:
  # Enable version updates for Maven
  - package-ecosystem: "maven"
    # Look for `pom.xml` in the `root` directory
    directory: "/"
    # Check the Maven registry for updates every day (weekdays)
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/yarspg"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/parsers/java"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/parsers/python"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every day (weekdays)
      interval: "daily"
